/* ============================================================
   data.js — All site content data
   ============================================================ */

/* ----- CV RAMAN BLOCK FLOORS ----- */
const CVR_FLOORS = [
  { label: "Basement Floor", image: "cvr_basement.png", alt: "CV Raman Block basement floor plan" },
  { label: "Ground Floor", image: "cvr_ground_floor.png", alt: "CV Raman Block ground floor plan" },
  { label: "1st Floor", image: "cvr_1st_floor.png", alt: "CV Raman Block 1st floor plan" },
  { label: "2nd Floor", image: "cvr_2nd_floor.png", alt: "CV Raman Block 2nd floor plan" },
  { label: "3rd Floor", image: "cvr_3rd_floor.png", alt: "CV Raman Block 3rd floor plan" },
  { label: "4th Floor", image: "cvr_4th_floor.png", alt: "CV Raman Block 4th floor plan" },
  { label: "5th Floor", image: "cvr_5th_floor.png", alt: "CV Raman Block 5th floor plan" },
];

/* ----- TEACHERS ----- */
/* Each object = one teacher row.
   letter: the alphabet group divider (set on first of each group, else "")
   name: full name
   dept: department (empty string if unknown)
   location: room/floor location (empty string if unknown) */
const TEACHERS = [
  { letter: "A", name: "Dr. A K Somayaji", dept: "", location: "" },
  { letter: "", name: "Dr. Aarti S Bhat", dept: "", location: "" },
  { letter: "", name: "Mrs. Aishwarya D Shetty", dept: "", location: "" },
  { letter: "", name: "Mr. Ajit Hebbale", dept: "", location: "" },
  { letter: "", name: "Ms. Akshata K J Shetty", dept: "", location: "" },
  { letter: "", name: "Mrs. Akshata N M", dept: "", location: "" },
  { letter: "", name: "Dr. Anil Kumar H S", dept: "", location: "" },
  { letter: "", name: "Mrs. Anitha D Bayar", dept: "", location: "" },
  { letter: "", name: "Dr. Anitha Marina Colaco", dept: "", location: "" },
  { letter: "", name: "Mrs. Anjana Pai", dept: "", location: "" },
  { letter: "", name: "Dr. Ashish Singh", dept: "", location: "" },
  { letter: "", name: "Mr. Ashwin Shenoy M", dept: "", location: "" },
  { letter: "", name: "Ms. Ashwini D Y", dept: "", location: "" },
  { letter: "", name: "Dr. Ashwini Kumari", dept: "", location: "" },
  { letter: "", name: "Dr. Austin Dinesh", dept: "", location: "" },
  { letter: "B", name: "Mr. Bhaskara P", dept: "", location: "" },
  { letter: "", name: "Mrs. Bhavya D", dept: "", location: "" },
  { letter: "", name: "Mrs. Bhavya K", dept: "", location: "" },
  { letter: "", name: "Dr. Bhojaraja B E", dept: "", location: "" },
  { letter: "C", name: "Dr. Chaithra K", dept: "", location: "" },
  { letter: "", name: "Dr. Charishma", dept: "", location: "" },
  { letter: "", name: "Dr. Chinmai Shetty", dept: "ISE", location: "APJ Block, 5th floor" },
  { letter: "D", name: "Mrs. Deekshita K", dept: "", location: "" },
  { letter: "", name: "Mrs. Deepa K", dept: "", location: "" },
  { letter: "", name: "Mr. Devidas", dept: "", location: "" },
  { letter: "", name: "Mr. Dhananjay B", dept: "", location: "SMV Block, 3rd floor" },
  { letter: "", name: "Dr. Dilip Kumar", dept: "Mech", location: "Ramanujan Block, 3rd floor" },
  { letter: "", name: "Dr. Divijesh P", dept: "", location: "" },
  { letter: "", name: "Dr. Durga Prasad", dept: "", location: "" },
  { letter: "G", name: "Dr. Ganesh Kumar K", dept: "", location: "" },
  { letter: "", name: "Dr. Girija K P", dept: "", location: "" },
  { letter: "", name: "Dr. Girisha Joshi", dept: "", location: "" },
  { letter: "", name: "Mr. Gouthama Hebbar", dept: "", location: "" },
  { letter: "", name: "Dr. Grynal D'Mello", dept: "", location: "" },
  { letter: "", name: "Mr. Gururaj Acharya", dept: "", location: "" },
  { letter: "", name: "Mr. Gururaj K", dept: "", location: "" },
  { letter: "H", name: "Mrs. Harshita Bhat", dept: "", location: "" },
  { letter: "", name: "Dr. Harshita J", dept: "", location: "" },
  { letter: "J", name: "Dr. Janaradana Nayak", dept: "", location: "" },
  { letter: "", name: "Dr. Joy Elvine Martis", dept: "Humanities", location: "CV Raman Block, 3rd floor" },
  { letter: "", name: "Mrs. Joyline Priya Pinto", dept: "", location: "" },
  { letter: "K", name: "Mr. Karthik", dept: "", location: "" },
  { letter: "", name: "Dr. Kavitha S", dept: "", location: "" },
  { letter: "", name: "Dr. Krishnananda Shet", dept: "", location: "" },
  { letter: "", name: "Dr. Krishnaprasad", dept: "", location: "" },
  { letter: "", name: "Dr. Kumar H S", dept: "", location: "" },
  { letter: "L", name: "Dr. Louella C Goveas", dept: "", location: "" },
  { letter: "", name: "Dr. Latha Shenoy", dept: "", location: "" },
  { letter: "M", name: "Mr. Mahesh B L", dept: "", location: "" },
  { letter: "", name: "Mr. Manjunatha A S", dept: "", location: "" },
  { letter: "", name: "Dr. Manjunatha K B", dept: "", location: "" },
  { letter: "", name: "Dr. Melwyn R C", dept: "", location: "" },
  { letter: "", name: "Dr. Murari M S", dept: "", location: "" },
  { letter: "N", name: "Dr. Nagaraja B S", dept: "", location: "" },
  { letter: "", name: "Dr. Nandini K K", dept: "", location: "" },
  { letter: "", name: "Dr. Narasimha Marakala", dept: "", location: "" },
  { letter: "", name: "Mr. Naveen J", dept: "", location: "" },
  { letter: "", name: "Dr. Nayana Shetty", dept: "", location: "" },
  { letter: "", name: "Dr. Nithin", dept: "", location: "" },
  { letter: "", name: "Mrs. Nutana Shetty", dept: "", location: "" },
  { letter: "P", name: "Dr. Padmavathi K", dept: "", location: "" },
  { letter: "", name: "Dr. Pavan Kumar", dept: "", location: "" },
  { letter: "", name: "Mr. Pawan Hegde", dept: "", location: "" },
  { letter: "", name: "Mr. Pradeep Karanth", dept: "", location: "" },
  { letter: "", name: "Mr. Pradyumna G R", dept: "", location: "" },
  { letter: "", name: "Dr. Pramod Kumar P S", dept: "", location: "" },
  { letter: "", name: "Dr. Prashanti K S", dept: "", location: "" },
  { letter: "", name: "Dr. Preeti Salian", dept: "", location: "" },
  { letter: "", name: "Mr. Prithviraj Jain", dept: "", location: "" },
  { letter: "R", name: "Dr. Raghavendra Bairy", dept: "", location: "Ramanujan Block, 1st floor" },
  { letter: "", name: "Dr. Rajalakshmi Hegde", dept: "", location: "" },
  { letter: "", name: "Mrs. Rajashree", dept: "", location: "" },
  { letter: "", name: "Dr. Rakshith Kumar Shetty", dept: "", location: "" },
  { letter: "", name: "Dr. Ramakrishna B", dept: "", location: "" },
  { letter: "", name: "Dr. Ramakrishna N S S", dept: "", location: "SMV Block, 3rd floor" },
  { letter: "", name: "Dr. Ramesh Bhat", dept: "", location: "" },
  { letter: "", name: "Mr. Ramesh Rao", dept: "", location: "" },
  { letter: "", name: "Mrs. Ramya Shetty", dept: "", location: "" },
  { letter: "", name: "Mr. Ranjith Bhat", dept: "", location: "" },
  { letter: "", name: "Dr. Ranjitha", dept: "", location: "" },
  { letter: "", name: "Rashmi Naveen", dept: "", location: "" },
  { letter: "", name: "Dr. Ravi B", dept: "", location: "" },
  { letter: "", name: "Mr. Ravikiran Rao M", dept: "", location: "" },
  { letter: "", name: "Dr. Ravindra", dept: "", location: "" },
  { letter: "", name: "Dr. Roshan Naik", dept: "", location: "" },
  { letter: "", name: "Mr. Roshan Rai", dept: "", location: "" },
  { letter: "S", name: "S Shyam Kumar", dept: "", location: "" },
  { letter: "", name: "Ms. Sanchitha C M", dept: "", location: "" },
  { letter: "", name: "Dr. Santosh G", dept: "", location: "" },
  { letter: "", name: "Dr. Santosh Poojary", dept: "BT", location: "" },
  { letter: "", name: "Dr. Saritha Suvarna", dept: "", location: "" },
  { letter: "", name: "Dr. Sarvajith M S", dept: "", location: "CV Raman Block, 4th floor" },
  { letter: "", name: "Mrs. Shankari N", dept: "", location: "" },
  { letter: "", name: "Dr. Sharad M Hegde", dept: "", location: "" },
  { letter: "", name: "Mr. Sharath Kumar", dept: "ISE", location: "Atal Block, 2nd floor" },
  { letter: "", name: "Dr. Sharathchandra S H", dept: "", location: "" },
  { letter: "", name: "Mrs. Sharmila Shetty", dept: "", location: "" },
  { letter: "", name: "Dr. Shivprasad Shetty", dept: "", location: "" },
  { letter: "", name: "Dr. Shobha R Prabhu", dept: "", location: "" },
  { letter: "", name: "Dr. Shreya Kanth", dept: "", location: "" },
  { letter: "", name: "Mrs. Shreya Shetty R", dept: "", location: "" },
  { letter: "", name: "Dr. Shrividya G", dept: "", location: "" },
  { letter: "", name: "Dr. Shubha B", dept: "", location: "" },
  { letter: "", name: "Ms. Shwetha Bharath", dept: "", location: "" },
  { letter: "", name: "Dr. Shyam Prasad K", dept: "", location: "" },
  { letter: "", name: "Mrs. Smitha G V", dept: "", location: "CV Raman Block, 3rd floor" },
  { letter: "", name: "Mrs. Soumya", dept: "", location: "" },
  { letter: "", name: "Mrs. Sowmya S", dept: "", location: "" },
  { letter: "", name: "Mr. Srinivas Nekkar", dept: "Humanities", location: "CV Raman Block, 2nd floor" },
  { letter: "", name: "Dr. Subrahmanya I Bhat", dept: "", location: "" },
  { letter: "", name: "Mr. Sudarshan", dept: "", location: "" },
  { letter: "", name: "Mrs. Sunitha Lasrado", dept: "", location: "" },
  { letter: "", name: "Dr. Suresh Shetty", dept: "", location: "" },
  { letter: "", name: "Dr. Sushma P S", dept: "", location: "" },
  { letter: "", name: "Ms. Swathi K", dept: "", location: "" },
  { letter: "U", name: "Dr. U Harshini", dept: "", location: "" },
  { letter: "", name: "Dr. Udaya", dept: "", location: "" },
  { letter: "V", name: "Dr. Vaikunt Pai", dept: "", location: "" },
  { letter: "", name: "Ms. Vaishali Bangera", dept: "", location: "" },
  { letter: "", name: "Dr. Vandana B S", dept: "ISE", location: "SMV, 1st floor" },
  { letter: "", name: "Dr. Venkataramana P B", dept: "", location: "" },
  { letter: "", name: "Dr. Vidya Kudva", dept: "", location: "" },
  { letter: "", name: "Dr. Vidya S M", dept: "", location: "" },
  { letter: "", name: "Dr. Vidyasagar Shetty", dept: "", location: "" },
  { letter: "", name: "Mrs. Vinaya Acharya", dept: "", location: "" },
  { letter: "", name: "Dr. Vishwanath J S", dept: "", location: "" },
  { letter: "", name: "Dr. Vishwanatha", dept: "", location: "" },
];

/* ----- SITE NAV LINKS ----- */
const NAV_LINKS = [
  { label: "C V Raman Block", href: "/pages/cvraman.html" },
  { label: "Teachers", href: "/pages/teachers.html" },
  { label: "II-Sem Timetable", href: "/pages/timetable.html" },
];

/* ----- SITE CREDITS ----- */
const CREDITS = [
  "Pratham Prabhakar"
];